In [140]:
%pip install opencv-python

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: opencv-python in c:\users\sarialop\anaconda3\lib\site-packages (4.7.0.72)



In [141]:
import numpy as np
import os
from sklearn.metrics import confusion_matrix
import seaborn as sn; sn.set(font_scale=1.4)
from sklearn.utils import shuffle           
import matplotlib.pyplot as plt             
import cv2                                 
import tensorflow as tf  
from tensorflow import convert_to_tensor              
from tqdm import tqdm
from PIL import Image
import urllib.request

In [142]:
# Cargamos los datos de los ficheros y los mostramos

import json


with open('pantalones.json', 'r') as p:
        pantalones = json.load(p)
print(type(pantalones))
print(len(pantalones))


with open('bicicletas.json', 'r') as b:
        bicicletas = json.load(b)
print(type(bicicletas))
print(len(bicicletas))
with open('televisiones.json', 'r') as t:
        televisiones = json.load(t)
print(type(televisiones))
print(len(televisiones))

with open('camisetas.json', 'r') as c:
        camisetas = json.load(c)
print(type(camisetas))
print(len(camisetas))

<class 'list'>
40
<class 'list'>
40
<class 'list'>
40
<class 'list'>
40


In [143]:
# Hacemos un dataframe con los datos de los dos ficheros

import pandas as pd

tododatos = pantalones + bicicletas + televisiones + camisetas

df = pd.DataFrame(tododatos)
df


id                                   title  \
0    wzy50mrwq5j5  Pantalón para de campana cuero marrón    
1    qzmywrkno1zv                             pantalones    
2    mzn8xyk91yzn                               pantalón    
3    e65glw2oypjo                               pantalón    
4    vjrr300ny4jk                     Pantalon Levi's 511   
..            ...                                     ...   
155  0j23l0wmee6y                           camiseta niña   
156  wzy503ryxpj5                      2 camisetas verano   
157  pj95l11lgvze                   camiseta del Valencia   
158  8j3el0end7z9                camiseta canibal corpse    
159  3zl17lv79qjx                        camiseta cadenas   

                                           description  distance  \
0    pantalón de cuero de pata de campana de color ...       1.0   
1    pantalones vaqueros de campana. Estan en muy b...       2.0   
2         talla 38 están nuevos me equivoque de talla        1.0   
3                    nuevo en perfecto estado, talla M      56.0   
4    Pantalon Levi's original en perfecto estado, g...       1.0   
..                                                 ...       ...   
155               Lote por 6. Talla 9 pero da una 7.\n       2.0   
156  Son bastante cómodas, se amolda a el cuerpo y ...       2.0   
157                      dañado por la zona del cuello       1.0   
158          manga corta , esta nueva , aceptó ofertas       2.0   
159                                sin uso . breschka       97.0   

                                                images  \
0    [{'original': 'http://cdn.wallapop.com/images/...   
1    [{'original': 'http://cdn.wallapop.com/images/...   
2    [{'original': 'http://cdn.wallapop.com/images/...   
3    [{'original': 'http://cdn.wallapop.com/images/...   
4    [{'original': 'http://cdn.wallapop.com/images/...   
..                                                 ...   
155  [{'original': 'http://cdn.wallapop.com/images/...   
156  [{'original': 'http://cdn.wallapop.com/images/...   
157  [{'original': 'http://cdn.wallapop.com/images/...   
158  [{'original': 'http://cdn.wallapop.com/images/...   
159  [{'original': 'http://cdn.wallapop.com/images/...   

                                                  user  \
0    {'id': 'p8j359kvgyz9', 'micro_name': '', 'imag...   
1    {'id': '8z81807o1r63', 'micro_name': '', 'imag...   
2    {'id': 'npj9k4v9kze7', 'micro_name': '', 'imag...   
3    {'id': 'p8j3e907m7z9', 'micro_name': '', 'imag...   
4    {'id': '9nz0r8dre7zo', 'micro_name': '', 'imag...   
..                                                 ...   
155  {'id': 'wzvyl1pyldzl', 'micro_name': '', 'imag...   
156  {'id': '8z818lpemr63', 'micro_name': '', 'imag...   
157  {'id': '0j2y4717rdzy', 'micro_name': '', 'imag...   
158  {'id': 'ejkxvkv0xy6x', 'micro_name': '', 'imag...   
159  {'id': 'kp615n0n07z5', 'micro_name': '', 'imag...   

                                                 flags  \
0    {'pending': False, 'sold': False, 'reserved': ...   
1    {'pending': False, 'sold': False, 'reserved': ...   
2    {'pending': False, 'sold': False, 'reserved': ...   
3    {'pending': False, 'sold': False, 'reserved': ...   
4    {'pending': False, 'sold': False, 'reserved': ...   
..                                                 ...   
155  {'pending': False, 'sold': False, 'reserved': ...   
156  {'pending': False, 'sold': False, 'reserved': ...   
157  {'pending': False, 'sold': False, 'reserved': ...   
158  {'pending': False, 'sold': False, 'reserved': ...   
159  {'pending': False, 'sold': False, 'reserved': ...   

                                      visibility_flags  price currency  ...  \
0    {'bumped': False, 'highlighted': False, 'urgen...  18.00      EUR  ...   
1    {'bumped': False, 'highlighted': False, 'urgen...  10.00      EUR  ...   
2    {'bumped': False, 'highlighted': False, 'urgen...   5.00      EUR  ...   
3    {'bumped': False, 'highlighted': False, 'urgen...   3

In [144]:
# Eliminamos las columnas que no nos interesan
df_todosdatos = df.drop(['price', 'description'], axis=1)

df_todosdatos
# Aplicamos la función que hemos creado en el paso anterior a la columna title del dataframe
df_todosdatos['title'] = df_todosdatos.apply(lambda x: x['title'].lower(), axis=1)

df_todosdatos

id                                   title  distance  \
0    wzy50mrwq5j5  pantalón para de campana cuero marrón        1.0   
1    qzmywrkno1zv                             pantalones        2.0   
2    mzn8xyk91yzn                               pantalón        1.0   
3    e65glw2oypjo                               pantalón       56.0   
4    vjrr300ny4jk                     pantalon levi's 511       1.0   
..            ...                                     ...       ...   
155  0j23l0wmee6y                           camiseta niña       2.0   
156  wzy503ryxpj5                      2 camisetas verano       2.0   
157  pj95l11lgvze                   camiseta del valencia       1.0   
158  8j3el0end7z9                camiseta canibal corpse        2.0   
159  3zl17lv79qjx                        camiseta cadenas      97.0   

                                                images  \
0    [{'original': 'http://cdn.wallapop.com/images/...   
1    [{'original': 'http://cdn.wallapop.com/images/...   
2    [{'original': 'http://cdn.wallapop.com/images/...   
3    [{'original': 'http://cdn.wallapop.com/images/...   
4    [{'original': 'http://cdn.wallapop.com/images/...   
..                                                 ...   
155  [{'original': 'http://cdn.wallapop.com/images/...   
156  [{'original': 'http://cdn.wallapop.com/images/...   
157  [{'original': 'http://cdn.wallapop.com/images/...   
158  [{'original': 'http://cdn.wallapop.com/images/...   
159  [{'original': 'http://cdn.wallapop.com/images/...   

                                                  user  \
0    {'id': 'p8j359kvgyz9', 'micro_name': '', 'imag...   
1    {'id': '8z81807o1r63', 'micro_name': '', 'imag...   
2    {'id': 'npj9k4v9kze7', 'micro_name': '', 'imag...   
3    {'id': 'p8j3e907m7z9', 'micro_name': '', 'imag...   
4    {'id': '9nz0r8dre7zo', 'micro_name': '', 'imag...   
..                                                 ...   
155  {'id': 'wzvyl1pyldzl', 'micro_name': '', 'imag...   
156  {'id': '8z818lpemr63', 'micro_name': '', 'imag...   
157  {'id': '0j2y4717rdzy', 'micro_name': '', 'imag...   
158  {'id': 'ejkxvkv0xy6x', 'micro_name': '', 'imag...   
159  {'id': 'kp615n0n07z5', 'micro_name': '', 'imag...   

                                                 flags  \
0    {'pending': False, 'sold': False, 'reserved': ...   
1    {'pending': False, 'sold': False, 'reserved': ...   
2    {'pending': False, 'sold': False, 'reserved': ...   
3    {'pending': False, 'sold': False, 'reserved': ...   
4    {'pending': False, 'sold': False, 'reserved': ...   
..                                                 ...   
155  {'pending': False, 'sold': False, 'reserved': ...   
156  {'pending': False, 'sold': False, 'reserved': ...   
157  {'pending': False, 'sold': False, 'reserved': ...   
158  {'pending': False, 'sold': False, 'reserved': ...   
159  {'pending': False, 'sold': False, 'reserved': ...   

                                      visibility_flags currency  \
0    {'bumped': False, 'highlighted': False, 'urgen...      EUR   
1    {'bumped': False, 'highlighted': False, 'urgen...      EUR   
2    {'bumped': False, 'highlighted': False, 'urgen...      EUR   
3    {'bumped': False, 'highlighted': False, 'urgen...      EUR   
4    {'bumped': False, 'highlighted': False, 'urgen...      EUR   
..                                                 ...      ...   
155  {'bumped': False, 'highlighted': False, 'urgen...      EUR   
156  {'bumped': False, 'highlighted': False, 'urgen...      EUR   
157  {'bumped': False, 'highlighted': False, 'urgen...      EUR   
158  {'bumped': False, 'highlighted': False, 'urgen...      EUR   
159  {'bumped': False, 'highlighted': False, 'urgen...      EUR   

     free_shipping                                         web_slug  ...  \
0            False  pantalon-para-de-campana-cuero-marron-883281244  ...   
1            False                             pantalones-883111308  ...   
2            False                    

In [145]:
url = df_todosdatos['images'].iloc[0]
print(url)

[{'original': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'xsmall': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W320', 'small': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W320', 'large': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'medium': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W640', 'xlarge': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'original_width': 0, 'original_height': 0}, {'original': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180295.jpg?pictureSize=W800', 'xsmall': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180295.jpg?pictureSize=W320', 'small': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i31911

In [146]:
# Creamos una función que nos permita cargar las imágenes
def load_image(row):
  try:
    imagen = urllib.request.urlopen(row['images'])
    img_pil = Image.open(imagen)
    img_np = np.array(img_pil)
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    
    return img_np
  except: return None

In [147]:
imagen = urllib.request.urlopen("http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800")
img_pil = Image.open(imagen)
img_np = np.array(img_pil)

print(img_np)

[[[179 183 184]
  [179 183 184]
  [180 184 185]
  ...
  [179 179 179]
  [179 179 179]
  [179 179 179]]

 [[180 184 185]
  [180 184 185]
  [180 184 185]
  ...
  [179 179 179]
  [179 179 179]
  [179 179 179]]

 [[180 184 185]
  [180 184 185]
  [180 184 185]
  ...
  [180 180 180]
  [179 179 179]
  [179 179 179]]

 ...

 [[145 135 126]
  [145 135 126]
  [145 135 126]
  ...
  [146 141 135]
  [146 141 135]
  [146 141 135]]

 [[145 135 126]
  [145 135 126]
  [145 135 126]
  ...
  [146 141 135]
  [146 141 135]
  [146 141 135]]

 [[144 134 125]
  [145 135 126]
  [145 135 126]
  ...
  [147 142 136]
  [147 142 136]
  [146 141 135]]]


In [148]:
# Aplicamos la función que hemos creado en el paso anterior a la columna images del dataframe para descargar todas las imágenes
df_todosdatos['images'] = df_todosdatos.apply(load_image, axis=1)
