In [13]:
%pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np
import seaborn as sn; sn.set(font_scale=1.4)                     
import cv2                                 
import tensorflow as tf              
from PIL import Image
import urllib.request

In [15]:
class_names = ['pantalon', 'bicicleta', 'television', 'camiseta']
IMAGE_SIZE = (100, 100)

In [16]:
# Cargamos los datos de los ficheros y los mostramos

import json


with open('pantalones.json', 'r') as p:
        pantalones = json.load(p)
print(type(pantalones))
print(len(pantalones))


with open('bicicletas.json', 'r') as b:
        bicicletas = json.load(b)
print(type(bicicletas))
print(len(bicicletas))
with open('televisiones.json', 'r') as t:
        televisiones = json.load(t)
print(type(televisiones))
print(len(televisiones))

with open('camisetas.json', 'r') as c:
        camisetas = json.load(c)
print(type(camisetas))
print(len(camisetas))

<class 'list'>
40
<class 'list'>
40
<class 'list'>
40
<class 'list'>
40


In [17]:
# Hacemos un dataframe con los datos de los dos ficheros

import pandas as pd

tododatos = pantalones + bicicletas + televisiones + camisetas

df = pd.DataFrame(tododatos)
df


id                                   title  ... taxonomy  discount
0    wzy50mrwq5j5  Pantalón para de campana cuero marrón   ...     None      None
1    qzmywrkno1zv                             pantalones   ...     None      None
2    mzn8xyk91yzn                               pantalón   ...     None      None
3    e65glw2oypjo                               pantalón   ...     None      None
4    vjrr300ny4jk                     Pantalon Levi's 511  ...     None      None
..            ...                                     ...  ...      ...       ...
155  0j23l0wmee6y                           camiseta niña  ...     None      None
156  wzy503ryxpj5                      2 camisetas verano  ...     None      None
157  pj95l11lgvze                   camiseta del Valencia  ...     None      None
158  8j3el0end7z9                camiseta canibal corpse   ...     None      None
159  3zl17lv79qjx                        camiseta cadenas  ...     None      None

[160 rows x 24 columns]

In [18]:
# Eliminamos las columnas que no nos interesan
df_todosdatos = df.drop(['price', 'description'], axis=1)

df_todosdatos
# Aplicamos la función que hemos creado en el paso anterior a la columna title del dataframe
df_todosdatos['title'] = df_todosdatos.apply(lambda x: x['title'].lower(), axis=1)

df_todosdatos

id                                   title  ...  taxonomy discount
0    wzy50mrwq5j5  pantalón para de campana cuero marrón   ...      None     None
1    qzmywrkno1zv                             pantalones   ...      None     None
2    mzn8xyk91yzn                               pantalón   ...      None     None
3    e65glw2oypjo                               pantalón   ...      None     None
4    vjrr300ny4jk                     pantalon levi's 511  ...      None     None
..            ...                                     ...  ...       ...      ...
155  0j23l0wmee6y                           camiseta niña  ...      None     None
156  wzy503ryxpj5                      2 camisetas verano  ...      None     None
157  pj95l11lgvze                   camiseta del valencia  ...      None     None
158  8j3el0end7z9                camiseta canibal corpse   ...      None     None
159  3zl17lv79qjx                        camiseta cadenas  ...      None     None

[160 rows x 22 columns]

In [19]:
url = df_todosdatos['images'].iloc[0]
print(url)

[{'original': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'xsmall': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W320', 'small': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W320', 'large': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'medium': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W640', 'xlarge': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800', 'original_width': 0, 'original_height': 0}, {'original': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180295.jpg?pictureSize=W800', 'xsmall': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180295.jpg?pictureSize=W320', 'small': 'http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i31911

In [20]:
# Creamos una función que nos permita cargar las imágenes
def load_image(row):
  try:
    imagen = urllib.request.urlopen(row['images'])
    img_pil = Image.open(imagen)
    img_np = np.array(img_pil)
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
    img_np = cv2.resize(img_np, IMAGE_SIZE)
    
    return img_np
  except: return None

In [21]:
imagen = urllib.request.urlopen("http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800http://cdn.wallapop.com/images/10420/el/vs/__/c10420p883281244/i3191180163.jpg?pictureSize=W800")
img_pil = Image.open(imagen)
img_np = np.array(img_pil)

print(img_np)

[[[179 185 185]
  [179 185 185]
  [179 185 185]
  ...
  [176 180 179]
  [176 180 179]
  [176 180 179]]

 [[179 185 185]
  [179 185 185]
  [179 185 185]
  ...
  [176 180 179]
  [176 180 179]
  [176 180 179]]

 [[179 185 185]
  [179 185 185]
  [180 186 186]
  ...
  [177 181 180]
  [176 180 179]
  [176 180 179]]

 ...

 [[146 136 127]
  [146 136 127]
  [146 136 127]
  ...
  [146 141 135]
  [146 141 135]
  [146 141 135]]

 [[146 136 127]
  [146 136 127]
  [146 136 127]
  ...
  [146 141 135]
  [146 141 135]
  [146 141 135]]

 [[144 134 125]
  [145 135 126]
  [144 134 125]
  ...
  [146 141 135]
  [146 141 135]
  [147 142 136]]]


In [22]:
# Aplicamos la función que hemos creado en el paso anterior a la columna images del dataframe para descargar todas las imágenes
df_todosdatos['images'] = df_todosdatos.apply(load_image, axis=1)


In [23]:
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
images = df_todosdatos['images']
title = df_todosdatos['title']

# Dividir los datos en conjuntos de entrenamiento y prueba
train_images, test_images, train_labels, test_labels = train_test_split(images, title, test_size=0.1, random_state=30)

# Mezclar los datos de entrenamiento
train_images, train_labels = shuffle(train_images, train_labels, random_state=25)

# Obtener el número de datos de entrenamiento y prueba
n_train = len(train_labels)
n_test = len(test_labels)

# Imprimir información
print("Número de datos de entrenamiento: {}".format(n_train))
print("Número de datos de prueba: {}".format(n_test))
print("Tamaño imagen: {}".format(IMAGE_SIZE))

Número de datos de entrenamiento: 144
Número de datos de prueba: 16
Cada imagen tiene un tamaño de: (100, 100)


In [24]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')


In [ ]:
from sklearn.model_selection import train_test_split
# Dividir los datos en conjuntos de entrenamiento y prueba
train_images, test_images, train_labels, test_labels = train_test_split(df_todosdatos['images'], df_todosdatos['category'], test_size=0.2, random_state=42)
train_images_tensor = []
for i in range(len(train_images)):
  train_images_tensor.append(tf.convert_to_tensor(train_images.iloc[i]))
np.array(train_images.tolist())

In [27]:
model.save('clf_imagenes.h5')